# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
